### ISSUE TITLE
Local custom .gguf modals supported?

### ISSUE THREAD

**Issue by sengiv** [tensorchord/modelz-llm#102]
Thanks for the repo, amazing work!🚀

possible to use GGUF modals made for **CPU**s like `llama-2-7b-chat.Q2_K.gguf`?

**Comment by kemingy** [comment]
We don't support this out-of-box. But you can use https://github.com/abetlen/llama-cpp-python to replace the model load and inference part in the following parts https://github.com/tensorchord/modelz-llm/blob/13770f88cec0c5670361bf7fe86fe3db27b6feca/src/modelz_llm/model.py#L44
https://github.com/tensorchord/modelz-llm/blob/13770f88cec0c5670361bf7fe86fe3db27b6feca/src/modelz_llm/model.py#L102-L109

It should work with these two changes.

**Comment by sengiv** [comment]
@kemingy thanks for the reply 🙏
If possible I'll try to make pull request so Modelz can support out of box (if you want to add this?)
