### ISSUE TITLE
feat: Support more models

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/modelz-llm#11]
- [x] LLaMA
- [x] Bloomz
- [x] ChatGLM 6B (non-int4)
- [x] Vicuna
- [ ] GPT-NeoX
- [ ] StarCoder
- [ ] MOSS

**Comment by kemingy** [comment]
There is no difference between the quantized model and the original model, at least for such a service.

**Comment by gaocegege** [comment]
Thus we need to update the env vars to THUDM/chatglm-6b, thus it should work, right?

**Comment by kemingy** [comment]
> Thus we need to update the env vars to THUDM/chatglm-6b, thus it should work, right?

It should work. I use the int4 because it's tiny to try.
