### ISSUE TITLE
feat: Support embedding API

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/modelz-llm#14]
Support this API: https://platform.openai.com/docs/api-reference/embeddings/create

Several endpoints:

- [ ] /engines/*/embeddings
- [ ] /v1/engines/*/embeddings
- [ ] /embeddings
- [ ] /v1/embeddings

**Comment by tddschn** [comment]
`engines` routes are deprecated, do we need to support them? https://platform.openai.com/docs/api-reference/engines
And those routes requires `engine_id`, what should `engine_id`s be?

**Comment by gaocegege** [comment]
Yeah we should support it because openai python SDK still uses it.
